name: Nuclei - Vulnerability Scan

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read
  issues: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@v3
        with:
          version: latest
          config: |
            target:
              - https://jubilant-engine-9r6r4qqjppqcr-3000.app.github.dev/
            severity:
              - critical
              - high
              - medium
            sarif-export: nuclei.sarif

      - name: Upload nuclei log artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nuclei-results
          path: nuclei.sarif

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: nuclei.sarif
          category: nuclei-results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
