name: Nuclei Scan

on:
  workflow_dispatch:

jobs:
  nuclei_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          wget https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei_3.3.7_linux_amd64.zip
          unzip nuclei_3.3.7_linux_amd64.zip
          sudo mv nuclei /usr/local/bin/
          nuclei -version

      - name: Update Templates
        run: nuclei -update-templates

      - name: Run Nuclei Scan
        run: |
          nuclei -u https://jubilant-engine-9r6r4qqjppqcr-3000.app.github.dev/ \
          -severity critical,high,medium \
          -o nuclei-report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: nuclei-report.txt
